config/routes.rb
Soccerty::Application.routes.draw do

  authenticated :user do
      root to: "home#index", as: :authenticated_root
  end

  root to: "visitors#index"
  get :join, to: "home#join"
  get :legal, to: "home#legal"
  get :about, to: "home#about"
  get :faq, to: "home#faq"

  devise_for :users

  resources :users do
    collection do
      get :orders
      get :feeds
      get :about_you
      get :ranking
      put :first_update
    end
  end

  resources :games do 
    collection do 
       get :new_chat
       get :map
       get :upcoming
       get :results
    end
  end

  resources :teams do
    collection do
      get :my
      post :invitation
      get :accept
    end
  end

  resources :series do 
    collection do 
      post :register_team
      post :register_individual
    end
  end

  resources :soccer_fields do
    collection do 
      get :retrieve
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	devise :database_authenticatable, :registerable, :omniauthable, 
		   :recoverable, :rememberable, :trackable, :validatable, :confirmable
	mount_uploader :picture, PictureUploader

	has_many :presences, dependent: :destroy
	has_many :games, through: :presences
	has_and_belongs_to_many :teams
	belongs_to :city
	has_many :game_chats
	has_many :feeds

	after_create { Feed.welcome(self) }

	def retrieve_user_games
		user_games = []
		games.each do |game|
			user_games << {id: game.id, title: "#{game.time.strftime('%I:%M %p')}", start: game.time, end: game.time+game.duration*60, duration: game.duration, allDay: true}
		end
		user_games
	end

	def rank
		User.valid(self.city_id).index(self) + 1 
	end

	def last_game
		games.where(status: 0).where("time < '#{Time.now}'").order("time DESC").first
	end

	def last_presence
		presences.joins(:game).where("games.status = 0").where("games.time < '#{Time.now}'").where(result: nil).order("time DESC").first
	end

	def played_games
		games.where("games.time < '#{Time.now}'").order("time DESC")
	end

	def games_with_results
		games.where(status: 1).order("time DESC")
	end

  def self.valid(city_id)
    where(city_id: city_id).where.not(first_name: nil).order("points DESC").order("id ASC")
  end

  def wins
  	wins = 0
  	presences.each {|p| wins += 1 if p.team == p.winner }
  	wins
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :auth_user, except: [:about_you, :first_update]

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = current_user
	end

	def update
		@user = User.find(params[:id])
		if @user.update(params[:user].permit(:position, :first_name, :last_name, :gender, :city_id, :level, :picture))
		  redirect_to @user, notice: 'Profile successfully updated.' 
		else
		  render action: :edit
		end
	end

	def orders
		@payments = current_user.payments.paginate(:page => params[:page], :per_page => 20)
	end

	def feeds
		@user = current_user
		@feeds = @user.feeds.order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
	end

	def about_you
		if not user_signed_in?
			redirect_to new_user_session_path, alert: "You need to sign in or sign up before continuing."
		else
			@user = current_user
			render layout: 'semi_raw'
		end
	end

	def first_update
		@user = User.find(params[:id])
		if @user.update(params[:user].permit(:position, :first_name, :last_name, :gender, :city_id, :level, :picture))
		  redirect_to root_path, notice: "Welcome #{@user.first_name} to Soccerty! Start by joining game(s)."
		else
		  render action: :edit
		end
	end

	def ranking
		@users = User.valid(current_user.city_id).paginate(:page => params[:page], :per_page => 20)
	end

end

app/views/users/about_you.html.erb
<%- title "Tell us more about yourself" %>
<%- message_type "col-md-8 col-md-offset-2" %>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <section class="widget">
            <header>
                <h4><i class="fa fa-info"></i> Info</h4>
            </header>
            <hr>
            <div class="body">
                <%= simple_form_for(@user, :as => @user, url: first_update_users_path(id: @user.id), :html => {class: "form-horizontal", :method => :put, 'data-validate' => "parsley", novalidate: "novalidate"}) do |f| %>
                    <%= render 'shared/errors', object: f.object %>                     
                        <fieldset>
                            <div class="control-group">
                                <label class="control-label">Position</label>
                                <div class="controls form-group">
                                    <div class="btn-group" data-toggle="buttons" required="required">
                                        <label class="btn <%= @user.position == 0 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input name="user[position]" type="radio" value="0"> Goalie 
                                        </label>
                                        <label class="btn <%= @user.position == 1 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input name="user[position]" type="radio" value="1"> Defender 
                                        </label>
                                        <label class="btn <%= @user.position == 2 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input name="user[position]" type="radio" value="2"> Midfielder
                                        </label>
                                        <label class="btn <%= @user.position == 3 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input name="user[position]" type="radio" value="2"> Striker
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Skill Level</label>
                                <div class="controls form-group">
                                    <div class="btn-group" data-toggle="buttons" required="required">
                                        <label class="btn <%= @user.level == 0 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input name="user[level]" type="radio" value="0"> Amateur 
                                        </label>
                                        <label class="btn <%= @user.level == 1 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input name="user[level]" type="radio" value="1"> Good 
                                        </label>
                                        <label class="btn <%= @user.level == 2 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input name="user[level]" type="radio" value="2"> Professional
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <%= f.input :first_name, placeholder: "Your first name", input_html: {class: "col-md-12", required: "required"}, label: "First Name" %>
                            <br>
                            <%= f.input :last_name, placeholder: "Your last name", input_html: {class: "col-md-12", required: "required"}, label: "Last Name" %>
                            <br>                        
                            <div class="control-group">
                                <label class="control-label">Gender</label>
                                <div class="controls form-group">
                                    <div class="btn-group" data-toggle="buttons">
                                        <label class="btn <%= @user.gender == 0 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input type="radio" name="user[gender]" value="0"> &nbsp; Male &nbsp;
                                        </label>
                                        <label class="btn <%= @user.gender == 1 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input type="radio" name="user[gender]" value="1"> Female
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    <div class="description">
                        <ul class="pager wizard">
                            <li class="finish">
                                <button class="btn btn-success pull-right" >Finish <i class="fa fa-check"></i></button>
                            </li>
                        </ul>
                    </div>
                <% end %>
            </div>
        </section>
    </div>
</div>

<% content_for :bottom do %>
    <script>
        $(function () {
            $(".btn-group > .btn[data-toggle-class]").click(function(){
                var $this = $(this),
                    isRadio = $this.find('input').is('[type=radio]'),
                    $parent = $this.parent();

                if (isRadio){
                    $parent.children(".btn[data-toggle-class]").removeClass(function(){
                        return $(this).data("toggle-class")
                    }).addClass(function(){
                            return $(this).data("toggle-passive-class")
                        });
                    $this.removeClass($(this).data("toggle-passive-class")).addClass($this.data("toggle-class"));
                } else {
                    $this.toggleClass($(this).data("toggle-passive-class")).toggleClass($this.data("toggle-class"));
                }
            });
            $("#wizard").bootstrapWizard({
                onTabClick: function(tab, navigation, index) {
                    return false;
                },
                onTabShow: function(tab, navigation, index) {
                    var $total = navigation.find('li').length;
                    var $current = index+1;
                    var $percent = ($current/$total) * 100;
                    var $wizard = $("#wizard");
                    $wizard.find('.progress-bar').css({width:$percent+'%'});

                    if($current >= $total) {
                        $wizard.find('.pager .next').hide();
                        $wizard.find('.pager .finish').show();
                        $wizard.find('.pager .finish').removeClass('disabled');
                    } else {
                        $wizard.find('.pager .next').show();
                        $wizard.find('.pager .finish').hide();
                    }
                },
                onNext: function(tab, navigation, index) {
                    if(index==2) {
                        if (!$('#user_first_name').parsley('validate') || !$('#user_last_name').parsley('validate')) return false;
                    } 
                }
            });
        });
    </script>
<% end %>

app/views/users/edit.html.erb
<%- title "Profile" %>
<%- page_category "Account" %>

<div class="row">
    <div class="col-md-8 col-sm-12">
        <section class="widget">
            <header>
                <h4><i class="fa fa-edit"></i> Edit Profile</h4>
            </header>
            <div class="body">
                <%= simple_form_for(@user, :as => @user, :html => {class: "form-horizontal label-left", :method => :put, :multipart => true }) do |f| %>
                    <fieldset>
                        <legend class="section">Personal Info</legend>
                        <%= f.input :first_name, placeholder: "Your first name", input_html: {class: "col-md-12"}, label: "First Name" %>
                        <br>
                        <%= f.input :last_name, placeholder: "Your last name", input_html: {class: "col-md-12"}, label: "Last Name" %>
                        <br>                        
                        <div class="control-group">
                            <label class="control-label">Gender</label>
                            <div class="controls form-group">
                                <div class="btn-group" data-toggle="buttons">
                                    <label class="btn <%= @user.gender == 0 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                        <input type="radio" name="user[gender]" value="0"> &nbsp; Male &nbsp;
                                    </label>
                                    <label class="btn <%= @user.gender == 1 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                        <input type="radio" name="user[gender]" value="1"> Female
                                    </label>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset>
                        <legend class="section">Player Profile</legend>
                        <%= f.input :position, label: "Favorite position", collection: {goalie: 0, defender: 1, midfielder: 2, striker: 3}, input_html: {class: "chzn-select select-block-level"}, selected: @user.position %>
                        <br>
                        <div class="control-group">
                            <label class="control-label">Skill Level</label>
                            <div class="controls form-group">
                                <div class="btn-group" data-toggle="buttons">
                                    <label class="btn <%= @user.level == 0 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                        <input name="user[level]" type="radio" value="0"> Amateur 
                                    </label>
                                    <label class="btn <%= @user.level == 1 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                        <input name="user[level]" type="radio" value="1"> Good 
                                    </label>
                                    <label class="btn <%= @user.level == 2 ? 'btn-primary active' : 'btn-default' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                        <input name="user[level]" type="radio" value="2"> Professional
                                    </label>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset>
                        <legend class="section"></legend>
                        <%= link_to "I would like to change my password", edit_user_registration_path %>
                    </fieldset>
                    <br>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Validate &amp; Submit</button>
                        <%= link_to "Cancel", @user, class: "btn btn-default"%>
                    </div>
                <% end %>
            </div>
        </section>
    </div>
    <div class="col-md-4 col-sm-12">
        <section class="widget">
            <header>
                <h4><i class="fa fa-picture-o"></i> Profile Picture</h4>
            </header>
            <div class="body">
                <%= simple_form_for(@user, :as => @user, :html => {id: "profile_picture", class: "form-horizontal label-left", :method => :put, :multipart => true }) do |f| %>
                    <fieldset>
                            <% unless @user.picture.url.nil? %> 
                                <%= image_tag(@user.picture.url(:thumb), style: "height:200px;width:100%;" ) %>
                            <% else %>
                                 <%= image_tag("default_profile_picture.png", style: "height:200px;width:100%;" ) %>
                            <% end %>
                        <hr>
                        <div class="control-group">
                            <span class="btn btn-sm btn-primary fileinput-button">
                                <i class="fa fa-picture-o"></i>
                                <span>Change profile picture</span>
                                <input type="file" name="user[picture]" multiple="">
                            </span>
                        </div>
                    </fieldset>
                <% end %>
            </div>
        </section>
    </div>
</div>

<% content_for :bottom do %>
    <script>
        $(function(){
            $('input[type=file]').change(function() { 
                $('#profile_picture').submit(); 
            });
            $(".btn-group > .btn[data-toggle-class]").click(function(){
                var $this = $(this),
                    isRadio = $this.find('input').is('[type=radio]'),
                    $parent = $this.parent();

                if (isRadio){
                    $parent.children(".btn[data-toggle-class]").removeClass(function(){
                        return $(this).data("toggle-class")
                    }).addClass(function(){
                            return $(this).data("toggle-passive-class")
                        });
                    $this.removeClass($(this).data("toggle-passive-class")).addClass($this.data("toggle-class"));
                } else {
                    $this.toggleClass($(this).data("toggle-passive-class")).toggleClass($this.data("toggle-class"));
                }
            });
        });
    </script>
<% end %>

app/views/users/feeds.html.erb
<%- title "Feeds" %>
<%- page_category "Account" %>
<%- message_type "col-md-8 col-md-offset-2" %>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <section class="widget">
            <header>
                <h4><i class="fa fa-rss"></i> <%= "#{@user.first_name} #{@user.last_name} "%>Feed</h4>
            </header>
            <div class="body">
                <div id="feed" class="feed">
                    <div class="wrapper">
                        <div class="vertical-line"></div>
                        <% @feeds.where(status: 0).each do |feed| %>
                            <section class="feed-item">
                                <div class="icon pull-left">
                                    <%= RoleHelper.feed_type(feed.feed_type).html_safe %>
                                </div>
                                <div class="feed-item-body">
                                    <div class="text">
                                        <%= feed.content.html_safe %>
                                    </div>
                                    <div class="time pull-left">
                                        <%= feed.created_at.strftime('%h %d %H:%M') %>
                                    </div>
                                </div>
                            </section>
                        <% end %>
                    </div>
                </div>
                <div class="clearfix">
                    <%= will_paginate @feeds, renderer: BootstrapPagination::Rails %>        
                </div>
            </div>
        </section>
    </div>
</div>

app/views/users/orders.html.erb
<%- title "Orders" %>
<%- page_category "Account" %>
<%- message_type "col-md-8 col-md-offset-2" %>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="alert alert-info alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong><i class="fa fa-info"></i> Tip:</strong>&nbsp;&nbsp;Contact us by email with the order id if you would like to cancel recent orders.
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <section class="widget">
            <header>
                <h4>
                    <i class="fa fa-money"></i>
                    Orders
                </h4>
            </header>
            <div class="body">
                <table class="table table-striped table-responsive table-images">
                    <thead>
                    <tr>
                        <th>Order ID</th>
                        <th>Date</th>
                        <th>Amount</th>
                        <th>Description</th>
                    </tr>
                    </thead>
                    <tbody>
                        <% @payments.each do |payment| %>
                            <tr>
                                <td><%= payment.id %></td>
                                <td><%= payment.created_at.strftime('%b %d %Y') %></td>
                                <td>$<%= payment.amount/100 %></td>
                                <td><%= payment.description %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            <div class="clearfix">
                <%= will_paginate @payments, renderer: BootstrapPagination::Rails %>        
            </div>
        </section>
    </div>
</div>

app/views/users/ranking.html.erb
<%- title "Players Ranking" %>
<%- page_category "Dashboard" %>

<%- message_type "col-md-8 col-md-offset-2" %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <section class="widget">
      <header>
          <h4>
              <i class="fa fa-list-ol"></i> Players Ranking
          </h4>
      </header>
      <div class="body">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Rank</th>
                <th>Name</th>
                <th>Points</th>
            </tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                    <tr>
                        <td><%= user.rank %></td>
                        <td><%= link_to "#{user.first_name} #{user.last_name[0,1]}.", user %></td>
                        <td><%= user.points %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <div class="clearfix">
            <%= will_paginate @users, renderer: BootstrapPagination::Rails %>        
        </div>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<%- title "Profile" %>
<%- page_category "Account" %>

<div class="row">
    <div class="col-md-12">
        <section class="widget">
            <div class="body no-margin">
                <div class="row">
                    <div class="col-md-6">
                        <h1><%= "#{@user.first_name} #{@user.last_name[0,1]}" %>
                            <%= link_to "<i class='fa fa-pencil-square-o'></i>&nbsp;&nbsp;Edit".html_safe, edit_user_path(@user), class: "btn btn-danger" if @user == current_user %>
                        </h1>
                    </div>
                    <div class="col-md-6">
                        <div class="pull-right">
                            <h2><%= RoleHelper.user_position(@user.position) %><h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

<div class="row">
    <div class="col-md-4 col-sm-12 col-xs-12">
        <div class="widget">
            <div class="profile_picture">
                <% unless @user.picture.url.nil? %> 
                    <%= image_tag @user.picture.url(:thumb), style: "height:200px;width:100%;" %>
                <% else %>
                     <%= image_tag "default_profile_picture.png", style: "height:200px;width:100%;" %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="col-md-8 col-sm-12 col-xs-12">
        <div class="body no-margin">
            <div class="row">
                <div class="col-md-4 col-sm-12 col-xs-12">
                    <div class="widget box1">
                        <span class="part3"><%= render "shared/stars", level: @user.level %></span><br>
                        <span class="part1"><%= RoleHelper.level(@user.level) %></span>
                    </div>
                </div>
                <div class="col-md-4 col-sm-12 col-xs-12">
                    <div class="widget box1">
                        <span class="part4"><i class="fa fa-trophy"></i></span><br>
                        <span class="part1"><strong><%= @user.points %></strong> points</span>
                    </div>
                </div>
                <div class="col-md-4 col-sm-12 col-xs-12">
                    <div class="widget box1">
                        <span class="part4"><%= @user.rank %></span><br>
                        <span class="part1"><i class="fa fa-flag-checkered"></i> city rank</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-sm-12 col-xs-12">
                    <div class="widget box1">
                        <%= @user.gender == 0 ? "<i class='fa fa-male fa-5x'></i>".html_safe : "<i class='fa fa-female fa-5x'></i>".html_safe  %>
                    </div> 
                </div>
                <div class="col-md-4 col-sm-12 col-xs-12">
                    <div class="widget box1">
                        <span class="part4"><i class="fa fa-thumbs-up"></i></span><br>
                        <span class="part1"><strong><%= @user.wins %></strong> wins</span>
                    </div>
                </div>
                <div class="col-md-4 col-sm-12 col-xs-12">
                    <div class="widget box1">
                        <span class="part4"><i class="fa fa-thumbs-down"></i></span><br>
                        <span class="part1"><strong><%= @user.games.where(status: 1).count - @user.wins %></strong> losses</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <section class="widget large">
            <header>
                <h4><i class="fa fa-bar-chart-o"></i> Performance</h4>
            </header>
            <div id="sources-chart-bar" class="body chart">
                <svg></svg>
            </div>
        </section>
    </div>
</div>

<% content_for :bottom do %>
    <script>
        var $lime = "#8CBF26",
        $red = "#e5603b",
        $redDark = "#d04f4f",
        $blue = "#6a8da7",
        $green = "#56bc76",
        $orange = "#eac85e",
        $pink = "#E671B8",
        $purple = "#A700AE",
        $brown = "#A05000",
        $teal = "#4ab0ce",
        $gray = "#666",
        $white = "#fff",
        $textColor = $gray;

        //turn off charts is needed
        var chartsOff = false;
        if (chartsOff){
            nv.addGraph = function(){};
        }

        COLOR_VALUES = [$red, $orange, $green, $blue, $teal, $redDark];

        var colors = function(){
            if (!window.d3) return false;
            return d3.scale.ordinal().range(COLOR_VALUES);
        }();

        function keyColor(d, i) {
            return colors(d.key)
        }

        var performance = JSON.parse('<%= @performance.to_json.html_safe%>');
        console.log(performance);

        nv.addGraph(function(){
            var chart = nv.models.multiBarChart()
                .margin({left: 30, bottom: 20, right: 0})
                .color(keyColor)
                .controlsColor([$white, $white, $white])
                .showLegend(false);

            chart.yAxis
                .showMaxMin(false)
                .ticks(0)
                .tickFormat(d3.format(',.f'));

            chart.xAxis
                .showMaxMin(false)
                .tickFormat(function(d) { return d3.time.format('%b %d %Y')(new Date(d)) });

            d3.select('#sources-chart-bar svg')
                .datum(performance)
                .transition().duration(500).call(chart);

            nv.utils.windowResize(chart.update);

            barChart = chart;

            return chart;
        });
    </script>
<% end %>