config/routes.rb
Soccerty::Application.routes.draw do

  authenticated :user do
      root to: "home#index", as: :authenticated_root
  end

  root to: "visitors#index"
  get :join, to: "home#join"
  get :legal, to: "home#legal"
  get :about, to: "home#about"
  get :faq, to: "home#faq"

  devise_for :users

  resources :users do
    collection do
      get :orders
      get :feeds
      get :about_you
      get :ranking
      put :first_update
    end
  end

  resources :games do 
    collection do 
       get :new_chat
       get :map
       get :upcoming
       get :results
    end
  end

  resources :teams do
    collection do
      get :my
      post :invitation
      get :accept
    end
  end

  resources :series do 
    collection do 
      post :register_team
      post :register_individual
    end
  end

  resources :soccer_fields do
    collection do 
      get :retrieve
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :auth_user, except: [:terms, :join]

  def index
    @user = current_user
    @games = @user.games
    @upcoming =  @games.where("games.time > '#{Time.now}'").order("time ASC").limit(5)
    @results =  @games.where(status: 1).order("time DESC").limit(5)
    if User.valid(@user.city_id).count < 5
      @users = User.valid(@user.city_id).limit(5)
    else
      max_offset = User.valid(@user.city_id).count-5 
      @users = User.valid(@user.city_id).offset(@user.rank-1 > max_offset ? max_offset : @user.rank-1).limit(5)
    end
    @next_game = @games.where("games.time > '#{Time.now}'").order("time ASC").first
    @join_suggestions = Serie.where("status < 2").order("start ASC").limit(3)
    finished_games = @user.games_with_results.count.to_f
    unless finished_games == 0
        @win_ratio = (@user.wins/finished_games*100).to_i
        @fun = (@user.fun/finished_games*100).to_i
        @presence = @user.last_presence
    end
    @feeds = current_user.feeds.order("created_at DESC").limit(5)
  end

  def legal
    render :layout => 'raw'
  end

  def join
    if user_signed_in?
      redirect_to series_path(id: params[:id])
    else
      redirect_to new_user_registration_path, notice: "To be able to register as an individual or a team you must first register as a Soccerty User" 
    end
  end

end

app/views/home/index.html.erb
<%- title "Dashboard" %>
<%- page_category "Dashboard" %>

<div class="row">
    <div class="col-md-7">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="widget box1">
                    <span class="part4">
                        <%= @user.rank %>
                    </span><br>
                    <span class="part1"><i class="fa fa-flag-checkered"></i>  city rank</span>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="widget box1">
                    <span class="part4"><i class="fa fa-trophy"></i></span><br>
                    <span class="part1"><strong><%= @user.points %></strong> points</span>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="widget box1">
                    <span class="part4"><i class="fa fa-thumbs-up"></i></span><br>
                    <span class="part1"><strong><%= @user.wins %></strong> wins</span>
                </div>
            </div>
        </div>
        <% unless @next_game.nil? %>
            <div class="row">
                <div class="col-md-12">
                    <section class="widget">
                        <header>
                            <h4><i class="fa fa-globe"></i> Next Game</h4>
                            <div class="actions">
                                <%= link_to raw("More <i class='fa fa-arrow-down'></i>"), @next_game, class: "btn btn-inverse btn-xs"%>
                            </div>
                        </header>
                        <div class="body">
                            <div class="box3 part2_5">
                                <%= @next_game.home.name %> 
                                <i class="fa fa-bolt fa-1x"></i> 
                                <%= @next_game.away.name %>
                                <br>
                                starts in <strong><%= @next_game.time_difference %></strong> at <strong><%= link_to raw("<i class='fa fa-map-marker'></i> #{@next_game.soccer_field.name}"), map_games_path(id: @next_game.soccer_field.id) %></strong>
                            </div>
                        </div>  
                    </section>
                </div>
            </div>
        <% end %>
        <% unless @join_suggestions.empty? %>
            <div class="row">
                <div class="col-md-12">
                    <section class="widget">
                        <header>
                            <h4><i class="fa fa-map-marker"></i> Join Leagues</h4>
                            <div class="actions">
                                <%= link_to raw("More <i class='fa fa-arrow-down'></i>"), series_index_path, class: "btn btn-inverse btn-xs"%>
                            </div>
                        </header>
                        <div class="body">
                            <%= render "series/table", series: @join_suggestions %>
                        </div>
                    </section>
                </div>
            </div>
        <% end %>
    </div>
    <div class="col-md-5">
        <section class="widget" style='max-height:400px;'>
            <header>
                <h4><i class="fa fa-rss"></i> Feed</h4>
                <div class="actions">
                    <%= link_to raw("More <i class='fa fa-arrow-down'></i>"), feeds_users_path, class: "btn btn-inverse btn-xs"%>
                </div>
            </header>
            <div class="body">
                <div id="feed" class="feed">
                    <div class="wrapper">
                        <div class="vertical-line"></div>
                        <% @feeds.each do |feed| %>
                            <section class="feed-item">
                                <div class="icon pull-left">
                                    <%= RoleHelper.feed_type(feed.feed_type).html_safe %>
                                </div>
                                <div class="feed-item-body">
                                    <div class="text">
                                        <%= feed.content.html_safe %>
                                    </div>
                                    <div class="time pull-left">
                                        <%= feed.created_at.strftime('%h %d %H:%M')  %>
                                    </div>
                                </div>
                            </section>
                        <% end %>
                    </div>
                </div>
            </div>
        </section>
        <section class="widget widget-tabs">
            <header>
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#ranking" data-toggle="tab">Ranking</a></li>
                    <% unless @upcoming.count == 0 %>
                        <li><a href="#games" data-toggle="tab">Upcoming</a></li>
                    <% end %>
                    <% unless @results.count == 0 %>
                        <li><a href="#results" data-toggle="tab">Results</a></li>
                    <% end %>
                </ul>
            </header>
            <div class="body tab-content">
                <div id="ranking" class="tab-pane active clearfix">
                    <table class="table table-striped">
                        <tbody>
                            <% @users.each do |user| %>
                                <tr>
                                    <td><%= user.rank %></td>
                                    <td><%= link_to "#{user.first_name} #{user.last_name[0,1]}.", user %></td>
                                    <td><%= user.points %></td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                    <%= link_to raw("More <i class='fa fa-arrow-down'></i>"), ranking_users_path, class: "btn btn-inverse btn-xs pull-right"%>
                </div>
                <div id="games" class="tab-pane clearfix">
                    <table class="table table-striped">
                        <tbody>
                            <% @upcoming.each do |game| %>
                                <tr style="text-align:center"> 
                                    <td><%= link_to "#{game.time.strftime('%b %d %Y')}", game %></td>
                                    <td><%= game.home.name %></td>
                                    <td><%= game.away.name %></td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                    <%= link_to raw("More <i class='fa fa-arrow-down'></i>"), upcoming_games_path, class: "btn btn-inverse btn-xs pull-right"%>
                </div>
                <div id="results" class="tab-pane clearfix">
                    <table class="table table-striped">
                        <tbody>
                            <% @results.each do |game| %>
                                <tr style="text-align:center"> 
                                    <td><%= link_to "#{game.time.strftime('%b %d %Y')}", game %></td>
                                    <td><%= game.home.name %> <%= raw(RoleHelper.winner_icon(game.result, 0)) %></td>
                                    <td><%= game.away.name %> <%= raw(RoleHelper.winner_icon(game.result, 1)) %></td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                    <%= link_to raw("More <i class='fa fa-arrow-down'></i>"), results_games_path, class: "btn btn-inverse btn-xs pull-right"%>
                </div>
            </div>
        </section>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 id ="myModalTitle" class="modal-title">Game Details</h4>
            </div>
            <div class="modal-body">
                <p>One fine body…</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<% content_for :bottom do %>
    <script>
        $(function(){
            $('input[type=file]').change(function() { 
                console.log("Hello");
                $('#profile_picture').submit(); 
            });
            $(".btn-group > .btn[data-toggle-class]").click(function(){
                var $this = $(this),
                    isRadio = $this.find('input').is('[type=radio]'),
                    $parent = $this.parent();

                if (isRadio){
                    $parent.children(".btn[data-toggle-class]").removeClass(function(){
                        return $(this).data("toggle-class")
                    }).addClass(function(){
                            return $(this).data("toggle-passive-class")
                        });
                    $this.removeClass($(this).data("toggle-passive-class")).addClass($this.data("toggle-class"));
                } else {
                    $this.toggleClass($(this).data("toggle-passive-class")).toggleClass($this.data("toggle-class"));
                }
            });
        });
    </script>
<% end %>