config/routes.rb
Soccerty::Application.routes.draw do

  authenticated :user do
      root to: "home#index", as: :authenticated_root
  end

  root to: "visitors#index"
  get :join, to: "home#join"
  get :legal, to: "home#legal"
  get :about, to: "home#about"
  get :faq, to: "home#faq"

  devise_for :users

  resources :users do
    collection do
      get :orders
      get :feeds
      get :about_you
      get :ranking
      put :first_update
    end
  end

  resources :games do 
    collection do 
       get :new_chat
       get :map
       get :upcoming
       get :results
    end
  end

  resources :teams do
    collection do
      get :my
      post :invitation
      get :accept
    end
  end

  resources :series do 
    collection do 
      post :register_team
      post :register_individual
    end
  end

  resources :soccer_fields do
    collection do 
      get :retrieve
    end
  end

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_filter :auth_user

  def index
    @series = Serie.where("status < 2").where("start > '#{Time.now}'").paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @serie = Serie.find(params[:id])
    @games = @serie.retrieve_games
  end

  def new
    @serie = Serie.new
    @serie.build_soccer_field
  end

  def create
    @serie = Serie.new(params[:serie].permit(:game_category, :level, :payment, :organizer_role, :recurring, :game_type, :game_cost, :number_games, :duration, :soccer_field_attributes => [:name, :address, :postal, :city_id, :category]))
    Time.zone = "EST"
    puts Time.zone.parse("2010-01-01 #{params[:serie][:time]}:00")
    @serie.time = Time.zone.parse("2010-01-01 #{params[:serie][:time]}:00")
    @serie.start = Time.zone.parse("#{params[:serie][:start]} 01:00:00")
    @serie.organizer = current_user
    if @serie.save
      redirect_to @serie, notice: "You've successfully setup your serie."
    else
      render :new
    end
  end

  def register_individual
    @serie = Serie.find(params[:id]) 
    @team = @serie.teams.first    
    @team.users << current_user
    @team.captain = current_user if @team.captain.nil?
    if @team.save
      Feed.joined_serie(current_user.id, @serie)
      redirect_to @serie, notice: "Hoorah! You've successfully registered to the serie. Game details will show up before your first game."
    end
  end

  def register_team
    @serie = Serie.find(params[:id])
    if current_user.series.include? @serie
      redirect_to @serie
    else      
       @serie.add_player(current_user)
       redirect_to @serie, notice: "Hoorah! You've successfully registered to the serie. Game details will show up before your first game."
    end
  end

end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_table.html.erb
<table class="table table-responsive table-striped table-images">
    <thead>
        <tr>
            <th>Level</th>
            <th>Day</th>
            <th>Location</th>
            <th>Start Date</th>
            <th>Type</th>
            <th># Games</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% series.each do |serie| %>
            <tr>
                <td><%= render "shared/stars", level: serie.level %></td>
                <td><%= serie.start.strftime('%A') %> Evenings</td>
                <td><%= serie.soccer_field.address %></td>
                <td><%= serie.start.strftime('%b %d %Y') %></td>
                <td><%= "#{serie.game_type}v#{serie.game_type} #{RoleHelper.serie_category(serie.game_category)}" %></td>
                <td><%= serie.number_games %></td>
                <td><%= link_to("join", join_path(id: serie.id), class: "btn btn-sm btn-primary") %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/series/checkout.html.erb
<%- title "Join Game(s)" %>
<%- message_type "col-md-8 col-md-offset-2" %>
<%- page_category "Games" %>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <section class="widget">
            <div class="body">
				    <%= form_tag participate_series_index_path(id: @serie.id), :class => "form-horizontal" do %>
                  <fieldset>
                      <legend class="section">Join Game(s) Confirmation.</legend>
                      <p>Payments cover the cost of the field and have to be paid on your first game.</p><br>
                      <label class="control-label" for="number_games">Number of games</label>
                      <div class="controls form-group">
                        <div class="input-group col-xs-12 col-sm-12 col-md-8">
                          <%= text_field_tag :number_games, @serie.number_games, class: "form-control", id: "number_games", :readonly => true %>
                        </div>
                      </div> 
                      <label class="control-label" for="game_cost">Cost per game</label>
                      <div class="controls form-group">
                        <div class="input-group col-xs-12 col-sm-12 col-md-8">
                          <%= text_field_tag :game_cost, @serie.game_cost, class: "form-control", id: "game_cost", :readonly => true %>
                        </div>
                      </div> 
                      <label class="control-label" for="total">Total</label>
                      <div class="controls form-group">
                          <div class="input-group col-xs-12 col-sm-12 col-md-8">
                              <span class="input-group-addon">$</span>
                              <%= text_field_tag :total, number_with_precision(@serie.number_games*@serie.game_cost, precision: 2), class: "form-control", id: "total", :readonly => true %>                                    
                           </div>
                      </div>
                      <%= hidden_field_tag :games, @games %>
                </fieldset>
                <div class="form-actions">
                    <div>
                        <button type="submit" class="btn btn-primary"> Confirm</button>
                        <%= link_to 'Cancel', @serie, class: "btn btn-default" %>
                    </div>
                </div>
	            <% end %>
            </div>
        </section>
    </div>
</div>

app/views/series/index.html.erb
<%- title "Join Leagues" %>
<%- page_category "Dashboard" %>

<div class="row">
    <div class="col-md-12">
        <section class="widget">
            <header>
                <h4>
                    <i class="fa fa-list-ol"></i>
                    Join Leagues
                </h4>
            </header>
            <div class="body">
                <%= render "series/table", series: @series %>
            <div class="clearfix">
                <%= will_paginate @series, renderer: BootstrapPagination::Rails %>        
            </div>
        </section>
    </div>
</div>

app/views/series/show.html.erb
<%- title "Join Serie" %>
<%- page_category "Series" %>

<div class="row">
    <div class="col-md-12">
        <section class="widget">
            <div class="body no-margin">
                <div class="row">
                    <div class="col-sm-6 col-print-6">
                        <h1> League #<%= @serie.id %></h1>
                    </div>
                    <div class="col-sm-6 col-print-6">
                        <div class="pull-right">
                            <h2><%= "#{@serie.game_type}v#{@serie.game_type} #{RoleHelper.serie_category(@serie.game_category)}" %></h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

<div class="row">
    <div class="col-md-2 col-sm-12 col-xs-12">
        <div class="widget box1">
            <span class="part3"><%= render "shared/stars", level: @serie.level %></span><br>
            <span class="part1"><%= RoleHelper.level(@serie.level) %></span>
        </div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-12">
        <div class="widget box1">
            <span class="part3"><%= @serie.duration %></span><br>
            <span class="part1"> minutes</span>
        </div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-12">
        <div class="widget box1">
            <span class="part1"><strong>$<%= @serie.team_price %></strong> team<br><strong>$<%= @serie.individual_price %></strong> individual</span>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="widget box1">
            <span class="part1"><strong><%= @serie.number_games %></strong> games in total</span><br>
            <span class="part1"><i class="fa fa-refresh"></i> every <strong><%= RoleHelper.serie_recurring(@serie.recurring) %></strong></span>
        </div>
    </div>
    <div class="col-md-3 col-sm-12 col-xs-12">
        <div class="widget box1" style="">
            <%= render "shared/joined", total: @serie.number_teams, joined: @serie.teams.count %>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6 col-sm-12 col-xs-12">
        <section class="widget">
            <div id="calendar" class="calendar"> </div>
        </section>
    </div>
    <div class="col-md-6 col-sm-12 col-xs-12">
        <section class="widget" style="height:345px">
            <header>
                <h4><i class="fa fa-map-marker"></i> <em><%= RoleHelper.soccer_field_category(@serie.soccer_field.category)%> </em><strong><%= @serie.soccer_field.name %></strong>. <%= @serie.soccer_field.address %>, <%= @serie.soccer_field.city.name %>.<br></h4>
                <a href="http://maps.google.com/?q=<%= @serie.soccer_field.full_address %>" target="_blank"> Open in Google Maps</a>
            </header>
            <div class="body" style="height:300px">
                <div class="map">
                    <div id="map"></div>
                </div>
            </div>
        </section>
    </div> 
</div>


<div class="row">
    <div class="col-md-12">
        <section class="widget" style="height:50px;">
            <div class="pull-left">
                <%= form_tag register_individual_series_index_path(id: @serie.id), id: "individual_form" %>
                <button id="individual" class="btn btn-primary btn-lg"><i class='fa fa-user'></i> Sign Up Indvidual</button>
            </div>
            <div class="pull-right">
                <%= form_tag register_team_series_index_path(id: @serie.id), id: "team_form" %>
                <button id="team" class="btn btn-primary btn-lg"><i class='fa fa-group'></i> Sign Up Team</button>
            </div>
        </section>
    </div>
</div>


<script src="https://checkout.stripe.com/v2/checkout.js" ></script>

<% content_for :bottom do %>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>
    <script>
        $(function(){
            $("#map").width("100%").height("100%").gmap3({
                marker:{
                  address: "<%= @serie.soccer_field.full_address %>"
                },
                map:{
                    options:{
                        zoom: 30,
                        mapTypeId: google.maps.MapTypeId.TERRAIN
                    }
                }
            });
            var date = new Date();
            var d = date.getDate();
            var m = date.getMonth();
            var y = date.getFullYear();
            var selected_games = [];
            var calendar = $('#calendar').fullCalendar({
                height: 345,
                header: {
                    left: 'prev',
                    center: 'title',
                    right: 'next'
                },

                selectable: true,
                selectHelper: true,
                select: function(start, end, allDay) {
                    var $modal = $("#edit-modal"),
                        $btn = $('#create-event');
                    $btn.off('click');
                    $btn.click(function () {
                        var title = $("#event-name").val();
                        if (title) {
                            calendar.fullCalendar('renderEvent',
                                {
                                    title: title,
                                    start: start,
                                    end: end,
                                    allDay: allDay
                                },
                                true
                            );
                        }
                        calendar.fullCalendar('unselect');
                    });
                    $modal.modal('show');
                    calendar.fullCalendar('unselect');
                },
                editable: false,
                droppable: false,
                events: JSON.parse('<%= @games.to_json.html_safe%>')
            });

            $("#calendar-switcher").find("label").click(function(){
                calendar.fullCalendar( 'changeView', $(this).find('input').val() )
            });
            $('#calendar').fullCalendar('gotoDate', new Date(Number(<%= @serie.start.to_i %>) * 1000));
        });
    $(function(){
      $('#individual').click(function(){
        var token = function(res){
        var $input = $('<input type=hidden name=stripeToken />').val(res.id);
            $('#individual_form').append($input).submit();
        };

        StripeCheckout.open({
            key:         "<%= Rails.configuration.stripe[:publishable_key] %>",
            address:     false,
            amount:      $('#individual_price').val()*100,
            currency:    'cad',
            name:        'League #<%= @serie.id %> Payment',
            panelLabel:  'Pay',
            token:       token
        });
        return false;
      });
    });
    </script>
<% end %>