config/routes.rb
Soccerty::Application.routes.draw do

  authenticated :user do
      root to: "home#index", as: :authenticated_root
  end

  root to: "visitors#index"
  get :join, to: "home#join"
  get :legal, to: "home#legal"
  get :about, to: "home#about"
  get :faq, to: "home#faq"

  devise_for :users

  resources :users do
    collection do
      get :orders
      get :feeds
      get :about_you
      get :ranking
      put :first_update
    end
  end

  resources :games do 
    collection do 
       get :new_chat
       get :map
       get :upcoming
       get :results
    end
  end

  resources :teams do
    collection do
      get :my
      post :invitation
      get :accept
    end
  end

  resources :series do 
    collection do 
      post :register_team
      post :register_individual
    end
  end

  resources :soccer_fields do
    collection do 
      get :retrieve
    end
  end

end

app/views/layouts/_brand.html.erb
<div class="logo">
    <h4><a href="/"><strong>SOCCERTY</strong></a></h4>
</div>

app/views/layouts/_header.html.erb
<ul class="nav navbar-nav navbar-right pull-right">
    <li>
        <%= form_tag destroy_user_session_path, method: :delete, id: "signout" do %><% end %>
        <%= link_to raw("<i class='fa fa-sign-out'></i>"), "#", :onclick => "$('#signout').submit()" %>    
    </li>
    <li class="visible-xs">
        <a href="#"
           class="btn-navbar"
           data-toggle="collapse"
           data-target=".sidebar"
           title="">
            <i class="fa fa-bars"></i>
        </a>
    </li>
</ul>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="<%= content_for?(:message_type) ? yield(:message_type) : 'col-md-12' %>">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          <% if name == :notice %>
            <strong><i class="fa fa-check"></i> </strong> 
          <% else %>
            <strong><i class="fa fa-ban"></i> </strong> 
          <% end %>
          <%= msg %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav id="sidebar" class="sidebar nav-collapse collapse">
  <ul id="side-nav" class="side-nav">  
    <li class="<%= yield(:page_category) == "Dashboard" ? 'active' : '' %> panel"><%= link_to raw("<i class='fa fa-home'></i> <span class='name'>Dashboard</span>"), root_path %></li>
    <li class="<%= yield(:title) == "Team" ? 'active' : '' %> panel">
        <%= link_to raw("<i class='fa fa-group'></i> <span class='name'>Team</span>"), my_teams_path %>
    </li>   
    <li class="<%= yield(:title) == "Calendar" ? 'active' : '' %> panel">
        <%= link_to raw("<i class='fa fa-calendar'></i> <span class='name'>Calendar</span>"), games_path %>
    </li>    
    <li class="<%= yield(:title) == "Profile" ? 'active' : '' %> panel">
        <%= link_to raw("<i class='fa fa-user'></i> <span class='name'>Profile</span>"), current_user %>
    </li>
    <li class="<%= yield(:title) == "Feeds" ? 'active' : '' %> panel">
        <%= link_to raw("<i class='fa fa-rss'></i> <span class='name'>Feed</span>"), feeds_users_path %>
    </li> 
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <title><%= content_for?(:title) ? yield(:title) : "Soccerty" %></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Maher Manoubi">
    <meta name="verifyownership" content="25cb785fe630af8b09dadad6257b22ed" />
    <meta charset="utf-8">
    <script type="text/javascript" src="//use.typekit.net/kgp1qmc.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <!--[if lt IE 10]>
      window.alert("Your browser is not compatible, update to latest version or user a modern browser such as Chrome.");
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/brand' %>
    <%= render 'layouts/navigation' %>

    <div class="wrap">
      <header class="page-header">
        <div class="navbar">
          <%= render 'layouts/header' %>
        </div>
      </header>
      <div class="content container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>


    <!-- starts javascript -->
    <%=javascript_include_tag "application" %> 
    
    <div id="bottom">
      <%= yield :bottom %>
    </div>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-34092700-2', 'soccerty.com');
      ga('send', 'pageview');
    </script>
    <!-- ends javascript -->
    
  </body>
</html>

app/views/layouts/visitor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <title><%= content_for?(:title) ? yield(:title) : "Soccerty" %></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Maher Manoubi">
    <meta name="verifyownership" content="25cb785fe630af8b09dadad6257b22ed" />
    <meta charset="utf-8">
    <%= yield :header %>
    <script type="text/javascript" src="//use.typekit.net/kgp1qmc.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  </head>

<body class="background landing">
  <div class="container">
    <header class="page-header">
        <div class="navbar">
            
        </div>
    </header>

    <%= yield %>
  </div>

    <!-- stars javascript -->
    <%=javascript_include_tag "application" %> 
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-34092700-2', 'soccerty.com');
      ga('send', 'pageview');
    </script>
    <!-- ends javascript -->


  </body>
</html>